kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishListView,
    CookListView,
    DishTypeListView,
    DishCreateView,
    CookCreateView,
    DishTypeCreateView,
    DishDetailView,
    CookDetailView,
    DishDeleteView,
    CookDeleteView,
    DishTypeDeleteView,
    DishUpdateView,
    CookUpdateView,
    DishTypeUpdateView,
    DishTypeDetailView,
    IngredientCreateView,
    IngredientListView,
    IngredientDetailView,
    IngredientUpdateView,
    IngredientDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/detail/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/detail/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dish-types/<int:pk>/detail/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail",
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "ingredients/create/", IngredientCreateView.as_view(), name="ingredient-create"
    ),
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path(
        "ingredients/<int:pk>/detail/",
        IngredientDetailView.as_view(),
        name="ingredient-detail",
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update",
    ),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/navigation.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-transparent bg-white shadow-none fixed-top" style="background-color: rgba(255, 255, 255, 0.85) !important;">
    <div class="container">
        <a class="navbar-brand text-dark" href="{% url 'kitchen:index' %}">
            <i class="fa fa-home me-2" style="color: #333;"></i>
            Home
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'kitchen:dish-list' %}">
                        <i class="fa fa-utensils me-2" style="color: #333;"></i>
                        All dishes
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'kitchen:dish-type-list' %}">
                        <i class="fa fa-plate-wheat me-2" style="color: #333;"></i>
                        Dish types
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'kitchen:cook-list' %}">
                        <i class="fa fa-user me-2" style="color: #333;"></i>
                        Cooks
                    </a>
                </li>
                <li class="nav-item dropdown mx-2">
                    <a class="nav-link ps-2 d-flex align-items-center text-dark" id="dropdownMenuAccount" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle me-2" style="color: #333;
                      "></i>
                        Account
                        <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-2">
                    </a>
                    <div class="dropdown-menu p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuAccount">
                        {% if user.is_authenticated %}
                            <h6 class="dropdown-header">Hello, {{ user.get_username }}</h6>
                            <form action="{% url 'logout' %}" method="post" style="display:inline;">
                                {% csrf_token %}
                                <button class="dropdown-item" type="submit">Logout</button>
                            </form>
                        {% else %}
                            <a href="{% url 'login' %}?next={{ request.path }}" class="dropdown-item">Login</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <div class="row text-center py-2">
    <div class="col-12::">
      <ul class="pagination pagination-primary m-4 d-flex justify-content-center" >
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
              <span aria-hidden="true">
                <i class="fa fa-angle-double-left" aria-hidden="true"></i>
              </span>
            </a>
          </li>
        {% endif %}

        {% for num in paginator.page_range %}
          {% if page_obj.number == num %}
            <li class="page-item active">
              <a class="page-link">{{ num }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?{% query_transform request page=num %}">{{ num }}</a>
            </li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
              <span aria-hidden="true">
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
              </span>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endif %}

templates/includes/scripts.html
{% load static %}

<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>