kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishListView,
    CookListView,
    DishTypeListView,
    DishCreateView,
    CookCreateView,
    DishTypeCreateView,
    DishDetailView,
    CookDetailView,
    DishDeleteView,
    CookDeleteView,
    DishTypeDeleteView,
    DishUpdateView,
    CookUpdateView,
    DishTypeUpdateView,
    DishTypeDetailView,
    IngredientCreateView,
    IngredientListView,
    IngredientDetailView,
    IngredientUpdateView,
    IngredientDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/detail/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/detail/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dish-types/<int:pk>/detail/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail",
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "ingredients/create/", IngredientCreateView.as_view(), name="ingredient-create"
    ),
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path(
        "ingredients/<int:pk>/detail/",
        IngredientDetailView.as_view(),
        name="ingredient-detail",
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update",
    ),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=69, unique=True)
    country = models.CharField(max_length=69, unique=False, blank=True, default="-")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(
        max_length=69,
        unique=True,
        validators=[
            RegexValidator(
                regex=r"^[a-zA-Z\s\-]+$",
                message="The name can only contain letters, spaces and dashes.",
            )
        ],
    )
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")
    ingredients = models.ManyToManyField("Ingredient", related_name="dishes")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Dish"
        verbose_name_plural = "Dishes"


class Ingredient(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        super().save(*args, **kwargs)
        return self.name

kitchen/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Dish, Cook, DishType, Ingredient


def validate_name(value):
    if not value.isalpha():
        raise ValidationError("This field should only contain letters")
    if len(value) < 2:
        raise ValidationError("This field should has 2 or more symbols ")


class DishForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = "__all__"
        widgets = {
            "ingredients": forms.CheckboxSelectMultiple(),
            "cooks": forms.CheckboxSelectMultiple(),
        }


class CookForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "years_of_experience",
        )

    first_name = forms.CharField(
        max_length=50,
        validators=[validate_name],
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    last_name = forms.CharField(
        max_length=50,
        validators=[validate_name],
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]


class DishTypeForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = "__all__"


class DishNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=55,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by dish name"}),
    )


class CookUsernameSearchForm(forms.Form):
    username = forms.CharField(
        max_length=55,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class DishTypeNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=55,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by dish type name"}),
    )


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = "__all__"


class IngredientNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=55,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by ingredient name"}),
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    DishForm,
    CookForm,
    DishTypeForm,
    CookUpdateForm,
    DishNameSearchForm,
    CookUsernameSearchForm,
    DishTypeNameSearchForm,
    IngredientForm,
    IngredientNameSearchForm,
)
from kitchen.models import Dish, Cook, DishType, Ingredient


def index(request: HttpRequest) -> HttpResponse:
    num_of_dishes = Dish.objects.count()
    num_of_cooks = Cook.objects.count()
    num_of_dish_types = DishType.objects.count()
    num_of_ingredients = Ingredient.objects.count()
    num_of_visits = request.session.get("num_of_visits", 0)
    request.session["num_of_visits"] = num_of_visits + 1

    context = {
        "num_of_dishes": num_of_dishes,
        "num_of_cooks": num_of_cooks,
        "num_of_dish_types": num_of_dish_types,
        "num_of_ingredients": num_of_ingredients,
        "num_of_visits": num_of_visits + 1,
    }
    return render(request, "kitchen/index.html", context=context)


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    queryset = Dish.objects.select_related("dish_type")

    def get_context_data(self, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishNameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = DishNameSearchForm(self.request.GET)

        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish

    def post(self, request, *args, **kwargs):
        dish = self.get_object()
        action = request.POST.get("action")
        if action == "assign_to_dish":
            dish.cooks.add(request.user)
        if action == "remove":
            dish.cooks.remove(request.user)
        return redirect("kitchen:dish-detail", pk=dish.pk)


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm

    def get_success_url(self):
        return reverse_lazy("kitchen:dish-detail", kwargs={"pk": self.object.pk})


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    template_name = "kitchen/dish_confirm_delete.html"


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5
    queryset = Cook.objects.prefetch_related("dishes")

    def get_context_data(self, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookUsernameSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = CookUsernameSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
            return queryset


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm

    def get_success_url(self):
        return reverse_lazy("kitchen:cook-detail", kwargs={"pk": self.object.pk})


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")
    template_name = "kitchen/cook_confirm_delete.html"


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeNameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = DishTypeNameSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
            return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeForm
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"
    context_object_name = "dish_type"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_confirm_delete.html"
    context_object_name = "dish_type"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    form_class = DishTypeForm
    template_name = "kitchen/dish_type_form.html"
    context_object_name = "dish_type"

    def get_success_url(self):
        return reverse_lazy("kitchen:dish-type-detail", kwargs={"pk": self.object.pk})


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    context_object_name = "dish_type"
    template_name = "kitchen/dish_type_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["dishes"] = Dish.objects.filter(dish_type=self.object)
        return context


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    form_class = IngredientForm
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    paginate_by = 25
    template_name = "kitchen/ingredient_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        name = self.request.GET.get("name", "")
        context["search_form"] = IngredientNameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = IngredientNameSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
            return queryset


class IngredientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Ingredient


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = "kitchen/ingredient_form.html"

    def get_success_url(self):
        return reverse_lazy("kitchen:ingredient-detail", kwargs={"pk": self.object.pk})


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("kitchen:ingredient-list")
    template_name = "kitchen/ingredient_confirm_delete.html"

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-8">
    <div class="card shadow-lg mx-auto" style="border-radius: 15px; max-width: 600px;">
      <div class="card-header bg-light text-white">
        <h3 class="text-center mb-0 text-dark">
          You really want to delete cook
          <i class="text-decoration-underline">{{ cook.first_name}} {{ cook.last_name }} ({{ cook.username }})</i>?
        </h3>

        <form action="" method="post">
          {% csrf_token %}
    
          <div class="mt-4 text-center">
            <input type="submit" value="Yes" class="btn btn-danger">
            <button type="button" class="btn btn-secondary" onclick="history.back()">Cancel</button>
          </div>

    
        </form>
      </div>
    </div>  
  </div>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div class="card shadow-lg mx-auto" style="border-radius: 15px; max-width: 600px;">
    <div class="card-header bg-light text-white">
      <h2 class="text-center mb-0 text-dark">
        {{ object.first_name }} {{ object.last_name }}
      </h2>
    </div>
    <div class="card-body text-muted">
      <p><strong>Username:</strong> {{ object.username }} </p>
      <p><strong>Email:</strong> {{ object.email }}</p>
      <p><strong>Experience:</strong> {{ object.years_of_experience }} year{{ object.years_of_experience|pluralize }}</p>
      {% if dish.dish_type.country %}
        <p><strong>Country:</strong> {{ object.dish_type.country }}</p>
      {% endif %}
      <a href="{% url 'kitchen:cook-update' object.pk %}" class="btn btn-warning">Edit</a>
      <a href="{% url 'kitchen:cook-delete' object.pk %}" class="btn btn-danger">Delete</a>
    

      <h3 class="mt-4">Prepared dishes</h3>
      <ul class="list-group mb-4">
        {% for dish in object.dishes.all %}
        <li class="list-group-item">
          <a href="{% url 'kitchen:dish-detail' dish.pk %}">
           {{ dish.name }}
          </a>
        </li>
        {% empty %}
        <li class="list-group-item">There are no dishes yet.</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-9">
    <h2 class="text-center m-md-4">
      {% if object %}
          {{ object.first_name }} {{ object.last_name }}
      {% else %}
          Register New Cook
      {% endif %}
    </h2>
    <div class="card shadow-lg mx-auto" style="max-width: 700px;">
      <div class="card-body">
        <form method="post" action="">
          {% csrf_token %}
          {% if form.errors %}
              {{ error }}
          {% endif %}
          {{ form|crispy }}
          <div class="text-center mt-3">
            <input type="submit" class="btn btn-success btn-lh" value="Submit">
            <input type="button" class="btn btn-secondary btn-lh" value="Cancel" onclick="window.history.back();">
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container mt-5">
  <h2 class="text-center mt-7 text-black">Cooks</h2>

  <form method="get" action="" class="form-inline mb-5">
    <div class="input-group" style="max-width: 600px; margin: auto;">
      {{ search_form.name.label_tag }}
      <input type="search" class="form-control text-black"
             placeholder="Search by username" aria-label="Search"
             aria-describedby="search-addon" name="name"
             value="{{ request.GET.name|default:'' }}"
             style="padding-left: 35px;">

      <button class="input-group-text border-0" id="search-addon" type="submit">
        <i class="fas fa-search"></i>
      </button>
    </div>
  </form>

  <a href="{% url 'kitchen:cook-create' %}" class="btn btn-info mb-3">
    Register New Cook
  </a>

  {% if object_list %}
  <div class="card shadow-2-strong" style="background-color: #f5f7fa; border-radius: 0.5rem;">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-borderless mb-0 text-center align-middle">
          <thead class="bg-light">
            <tr>
              <th>ID</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Username</th>
              <th>Years of Experience</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for cook in object_list %}
            <tr>
              <td>
                {{ cook.pk }}
              </td>
              <td>{{ cook.first_name }}</td>
              <td>{{ cook.last_name }}</td>
              <td>{{ cook.username }}</td>
              <td>{{ cook.years_of_experience }}</td>
              <td>
                <a href="{% url 'kitchen:cook-update' cook.pk %}" class="btn btn-warning btn-sm">Update</a>
                <a href="{% url 'kitchen:cook-detail' cook.pk %}" class="btn btn-primary btn-sm">View</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
    </div>
  </div>
  {% else %}
  <p>Cook not found.</p>
  {% endif %}
</div>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-8">
    <div class="card shadow-lg mx-auto" style="border-radius: 15px; max-width: 600px;">
      <div class="card-header bg-light text-white">
        <h3 class="text-center mb-0 text-dark">
          You really want to delete <i class="text-decoration-underline">{{ dish.name }}</i>?
        </h3>

        <form action="" method="post">
          {% csrf_token %}
    
          <div class="mt-4 text-center">
            <input type="submit" value="Yes" class="btn btn-danger">
            <button type="button" class="btn btn-secondary" onclick="history.back()">Cancel</button>
          </div>

    
        </form>
      </div>
    </div>  
  </div>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-9">
    <h2 class="text-center m-md-4">
      {% if object %}
          Update dish: {{ dish.name }}
      {% else %}
          Create new dish
      {% endif %}
    </h2>
    <div class="card shadow-lg">
      <div class="card-body">
        <form method="post" action="">
          {% csrf_token %}
          {% if form.errors %}
              {{ error }}
          {% endif %}
          {{ form|crispy }}
          <div class="text-center mt-3">
            <input type="submit" class="btn btn-success btn-lh" value="Submit">
            <input type="button" class="btn btn-secondary btn-lh" value="Cancel" onclick="window.history.back();">
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-8">
    <div class="card shadow-lg mx-auto" style="border-radius: 15px; max-width: 600px;">
      <div class="card-header bg-light text-center">
        <h3>Delete {{ dish_type.name }} ?</h3>
        <p>Are you sure you want to delete the dish type: <strong>{{ dish_type.name }}</strong> ?</p>
        <p class="text-danger"><i>All dishes of this type will be also deleted!</i></p>

        <form action="" method="post">
          {% csrf_token %}
          <div class="mt-4 text-center">
            <input type="submit" value="Yes" class="btn btn-danger">
            <button type="button" class="btn btn-secondary" onclick="history.back()">Cancel</button>
          </div>
        </form>
        
      </div>
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_type_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">

  <div class="card shadow-lg mx-auto" style="border-radius: 15px; max-width: 600px;">
    <div class="card-header bg-light text-white">
      <h2 class="text-center mb-0 text-dark">
        {{ object.name }}
      </h2>
    </div>
  
    <div class="card-body text-muted">
      <p><strong>County:</strong> {{ object.country }} </p>
      <p><strong>Amount of dishes:</strong> {{ object.dish_set.count }}</p>
      {% if dish.dish_type.country %}
        <p><strong>Country:</strong> {{ object.dish_type.country }}</p>
      {% endif %}
      <a href="{% url 'kitchen:dish-type-update' object.pk %}" class="btn btn-warning">Edit</a>
      <a href="{% url 'kitchen:dish-type-delete' object.pk %}" class="btn btn-danger">Delete</a>

      <h3 class="mt-4">Dishes</h3>
      <ul class="list-group mb-4">
        {% for dish in object.dish_set.all %}
        <li class="list-group-item">
          <a href="{% url 'kitchen:dish-detail' dish.pk %}">
           {{ dish.name }}
          </a>
        </li>
        {% empty %}
        <li class="list-group-item">No dishes yet.</li>
        {% endfor %}
      </ul>
    </div>
  
  </div>
</div>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <h2 class="text-center mt-7 text-black">All dish types</h2>

  <form method="get" action="" class="form-inline mb-5">
    <div class="input-group" style="max-width: 600px; margin: auto;">
      {{ search_form.name.label_tag }}
      <input type="search" class="form-control text-black"
             placeholder="Search by dish type name" aria-label="Search"
             aria-describedby="search-addon" name="name"
             value="{{ request.GET.name|default:'' }}"
             style="padding-left: 30px;">

      <button class="input-group-text border-0" id="search-addon" type="submit">
        <i class="fas fa-search"></i>
      </button>
    </div>
  </form>

  <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-info mb-3">
    Add new dish type
  </a>

  {% if object_list %}
  <div class="card shadow-2-strong" style="background-color: #f5f7fa; border-radius: 0.5rem;">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-borderless mb-0 text-center align-middle">
        
          <thead class="bg-light">
            <tr>
              <th>Dish type</th>
              <th>Country</th>
              <th>Amount of dishes</th>
            </tr>
          </thead>
        
          <tbody class="table">
            {% for dish_type in object_list %}
            <tr>
              <td>
                <a href="{% url 'kitchen:dish-type-detail' dish_type.pk %}">{{ dish_type.name }}</a>
              </td>
              <td>{{ dish_type.country }}</td>
              <td>{{ dish_type.dish_set.count }}</td>
            </tr>
            {% endfor %}
          </tbody>
        
        </table>
      </div>
    </div>
  </div>
  {% else %}
  <p>Dish type not found.</p>
  {% endif %}
</div>
  
{% endblock %}

templates/kitchen/ingredient_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div class="card shadow-lg mx-auto" style="border-radius: 15px; max-width: 600px;">
    <div class="card-header bg-light text-white">
      <h2 class="text-center mb-0 text-dark">{{ object.name }}</h2>
    </div>
    <div class="card-body text-muted">
      <a href="{% url 'kitchen:ingredient-update' object.pk %}" class="btn btn-warning">Edit</a>
      <a href="{% url 'kitchen:ingredient-delete' object.pk %}" class="btn btn-danger">Delete</a>

      <h3 class="mt-4">Dishes:</h3>
      <ul class="list-group mb-4">
        {% for dish in object.dishes.all %}
        <li class="list-group-item">
          <a href="{% url 'kitchen:dish-detail' dish.pk %}">
           {{ dish.name }}
          </a>
        </li>
        {% empty %}
        <li class="list-group-item">No dishes with this ingredient yet</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/kitchen/ingredient_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<body>
  <div class="container mt-7">
    <div class="d-flex justify-content-center align-items-center mb-2">
      <h1>Ingredients List</h1>
      <a href="{% url 'kitchen:ingredient-create' %}" class="btn btn-info ms-3">
        Add Ingredient
      </a>
    </div>

    <form method="get" action="" class="form-inline mb-3">
    <div class="input-group" style="max-width: 600px; margin: auto;">
      {{ search_form.name.label_tag }}
      <input type="search" class="form-control text-black"
             placeholder="Search by name" aria-label="Search"
             aria-describedby="search-addon" name="name"
             value="{{ request.GET.name|default:'' }}"
             style="padding-left: 30px;">
      <button class="input-group-text border-0" id="search-addon" type="submit">
        <i class="fas fa-search"></i>
      </button>
    </div>
    </form>

    <div class="row justify-content-center">
      <div class="col-6">
        <div class="list-group">

          {% for ingredient in object_list %}
            <i class="list-group-item list-group-item-action">
              <a href="{% url 'kitchen:ingredient-detail' ingredient.pk %}">{{ ingredient.name }}</a>
            </i>
          {% empty %}
            <div class="alert alert-warning text-center" role="alert">
              No ingredients found.
            </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}